services:
  db:
    image: postgres:16
    container_name: petclinic-db
    environment:
      POSTGRES_DB: veterinaria_pet_clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - petclinic-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: petclinic-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: veterinaria_pet_clinic
      DB_USER: postgres
      DB_PASSWORD: 12345
      SERVER_PORT: 8080
      MAIL_USERNAME: betodokij15@gmail.com
      MAIL_PASSWORD: "pmrg kaid zxcz elmz"
    ports:
      - "8080:8080"

volumes:
  petclinic-db-data: