spring.application.name=veterinaria-pet-clinic
logging.level.org.thymeleaf=DEBUG

# Puerto del servidor 
server.port=${SERVER_PORT:8080}

# PostgreSQL 
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:veterinaria_pet_clinic}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Configuración de Email 
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:betodokij15@gmail.com}
spring.mail.password=${MAIL_PASSWORD:pmrg kaid zxcz elmz}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Habilitar Programación de Tareas
spring.task.scheduling.pool.size=1


app.cancellation.phone=+51 918 470 481

# Horario de atención de la veterinaria
app.business.start-time=08:00
app.business.end-time=22:00

# Subida de archivos (imágenes de medicamentos)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB