spring.application.name=veterinaria-pet-clinic

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/veterinaria_pet_clinic
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Configuración de Email 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=betodokij15@gmail.com
spring.mail.password=tvap gldd fbfe silv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Habilitar Programación de Tareas
spring.task.scheduling.pool.size=1


app.cancellation.phone=+51 918 470 481

# Horario de atención de la veterinaria
app.business.start-time=08:00
app.business.end-time=22:00

# Subida de archivos (imágenes de medicamentos)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
