name: PetClinic CI

on:
  push:
    branches:
      - main
      - Administrador
      - Recepcionista
      - Veterinaria2
      - veterinaria
      - Farmaceutico
      - vendedor

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Compilar proyecto
        run: mvn clean compile

      - name: Ejecutar pruebas
        run: mvn test